version: '3.6'
services:
  postgres:
    restart: always
    image: ehiller/postgresql
    build:
      context: ./images/postgresql
      labels:
        - "pro.hiller.description=PostgreSQL on Windows with Volume; works with Windows Server 2019"
    env_file: ./env/postgres.env
    ports:
      - 5432:5432
    volumes:
      - postgres_database:C:\pgsql\data
    hostname: pg
    mac_address: "4E:00:00:00:00:20"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 30s
        timeout: 5s
        retries: 5
  pgadmin4:
    restart: unless-stopped
    image: ehiller/pgadmin:latest
    # image: ehiller/pgadmin4
    # build:
    #   context: ./images/pgadmin4
    #   labels:
    #     - "pro.hiller.description=pgAdmin 4 on Windows; works with Windows Server 2019"
    volumes:
      - pgadmin4:C:\data
    ports:
      - 80
      # - 8081:80
    mac_address: "4E:00:00:00:00:21"
    hostname: pgadmin
    env_file: ./env/pgadmin4.env
    # healthcheck is in the Dockerfile

networks:
 default:
  external:
    # name: "nat"
    name: "Mellanox ConnectX-3 Pro Ethernet Adapter #2 - Virtual Switch"

## Created first with 
##   docker volume create --name=postgres_database
## May not be necessary to do this (or make it external)
volumes:
  postgres_database:
  pgadmin4:
        # external: true