version: '3.6'
services:
  postgres:
    restart: always
    image: ehiller/postgresql
    build:
      context: .
      labels:
        - "pro.hiller.description=PostgreSQL on Windows with Volume; works with Windows Server 2016"
    env_file: ./env/postgres.env
    ports:
      - 5432:5432
    volumes:
      - postgres_database:C:\pgsql\data
    hostname: pg

    # volumes:
    #   - postgres_database:C:/sql:rw
      # - S:/virtual_machines/containers/postgresql:C:/sql:RW

    # links:
    # - pgadmin4
  pgadmin4:
    image: ehiller/pgadmin4
    build:
      context: ./pgadmin4
      labels:
        - "pro.hiller.description=pgAdmin 4 on Windows; works with Windows Server 2016"
    volumes:
      - pgadmin4:C:\data
    ports:
      - 8081:80
    env_file: .env

# networks:
  # default:
    # driver: transparent
#     driver_opts: 
#       com.docker.network.windowsshim.interface: "Ethernet 2"
      # gateway: ${NETWORK_GATEWAY}
    # enable_ipv6: false
    # ipam:
    #   config:
    #   - subnet: ${NETWORK_V4}
networks:
 default:
  external:
    name: "nat"
  #  name: "External on Dedicated I219"

## Created first with 
##   docker volume create --name=postgres_database
## May not be necessary to do this (or make it external)
volumes:
  postgres_database:
  pgadmin4:
        # external: true